In [26]:
from tensorflow.keras.preprocessing.text import one_hot

In [27]:
### sentences

sent = [
    'I believe in constant growth',
    'I believe in constant Decline ',
    'Practice makes perfect',
    'Coding makes ideas come alive',
    'Success comes from daily effort',
    'Stay curious and keep exploring',
    'Hard work always beats talent',
    'Believe in yourself',
    'Focus brings clarity and direction',
    'Stay focused always',
]

In [28]:
sent

['I believe in constant growth',
 'I believe in constant Decline ',
 'Practice makes perfect',
 'Coding makes ideas come alive',
 'Success comes from daily effort',
 'Stay curious and keep exploring',
 'Hard work always beats talent',
 'Believe in yourself',
 'Focus brings clarity and direction',
 'Stay focused always']

In [29]:
# define the vacalbulary size 
voc_size = 10000

In [30]:
# One Hot Representation 
one_hot_representation=[one_hot(words,voc_size)for words in sent]
one_hot_representation

# o/p = only index

[[1850, 232, 289, 494, 4704],
 [1850, 232, 289, 494, 2983],
 [6753, 9878, 3888],
 [8897, 9878, 6068, 6043, 6881],
 [9754, 7071, 506, 2448, 5613],
 [313, 1949, 3340, 8127, 6076],
 [38, 7017, 8950, 4765, 6285],
 [232, 289, 2189],
 [2752, 6425, 2174, 3340, 336],
 [313, 5146, 8950]]

In [31]:
## Word Embedding Representation

from tensorflow.keras.layers import Embedding
# from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential


In [32]:
import numpy as np

In [35]:
sent_length = 10
embedded_doc = pad_sequences(one_hot_representation,padding='pre', maxlen=sent_length)
print(embedded_doc)

[[   0    0    0    0    0 1850  232  289  494 4704]
 [   0    0    0    0    0 1850  232  289  494 2983]
 [   0    0    0    0    0    0    0 6753 9878 3888]
 [   0    0    0    0    0 8897 9878 6068 6043 6881]
 [   0    0    0    0    0 9754 7071  506 2448 5613]
 [   0    0    0    0    0  313 1949 3340 8127 6076]
 [   0    0    0    0    0   38 7017 8950 4765 6285]
 [   0    0    0    0    0    0    0  232  289 2189]
 [   0    0    0    0    0 2752 6425 2174 3340  336]
 [   0    0    0    0    0    0    0  313 5146 8950]]


In [37]:
# feature representation
dim =10

In [41]:
model=Sequential()
model.add(Embedding(voc_size, dim,input_length=sent_length))
model.compile('adam', 'mse')

In [43]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 10, 10)            100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
model.predict(embedded_doc)
# o/p = 10 dimention 

1/1 [==============================] - 0s 209ms/step


array([[[ 3.21386494e-02, -4.45466042e-02, -4.87008356e-02,
         -6.19130209e-03,  4.63744663e-02, -1.62151344e-02,
         -7.51050562e-03,  3.88259776e-02,  4.71024029e-02,
          2.22788118e-02],
        [ 3.21386494e-02, -4.45466042e-02, -4.87008356e-02,
         -6.19130209e-03,  4.63744663e-02, -1.62151344e-02,
         -7.51050562e-03,  3.88259776e-02,  4.71024029e-02,
          2.22788118e-02],
        [ 3.21386494e-02, -4.45466042e-02, -4.87008356e-02,
         -6.19130209e-03,  4.63744663e-02, -1.62151344e-02,
         -7.51050562e-03,  3.88259776e-02,  4.71024029e-02,
          2.22788118e-02],
        [ 3.21386494e-02, -4.45466042e-02, -4.87008356e-02,
         -6.19130209e-03,  4.63744663e-02, -1.62151344e-02,
         -7.51050562e-03,  3.88259776e-02,  4.71024029e-02,
          2.22788118e-02],
        [ 3.21386494e-02, -4.45466042e-02, -4.87008356e-02,
         -6.19130209e-03,  4.63744663e-02, -1.62151344e-02,
         -7.51050562e-03,  3.88259776e-02,  4.710240

In [46]:
embedded_doc[0]

array([   0,    0,    0,    0,    0, 1850,  232,  289,  494, 4704])

In [49]:
model.predict(embedded_doc[0])

1/1 [==============================] - 0s 57ms/step


array([[ 0.03213865, -0.0445466 , -0.04870084, -0.0061913 ,  0.04637447,
        -0.01621513, -0.00751051,  0.03882598,  0.0471024 ,  0.02227881],
       [ 0.03213865, -0.0445466 , -0.04870084, -0.0061913 ,  0.04637447,
        -0.01621513, -0.00751051,  0.03882598,  0.0471024 ,  0.02227881],
       [ 0.03213865, -0.0445466 , -0.04870084, -0.0061913 ,  0.04637447,
        -0.01621513, -0.00751051,  0.03882598,  0.0471024 ,  0.02227881],
       [ 0.03213865, -0.0445466 , -0.04870084, -0.0061913 ,  0.04637447,
        -0.01621513, -0.00751051,  0.03882598,  0.0471024 ,  0.02227881],
       [ 0.03213865, -0.0445466 , -0.04870084, -0.0061913 ,  0.04637447,
        -0.01621513, -0.00751051,  0.03882598,  0.0471024 ,  0.02227881],
       [-0.04680209, -0.03907343,  0.01064682, -0.01538538,  0.02334261,
        -0.0253294 , -0.00148494,  0.00424476,  0.0419896 ,  0.02809649],
       [-0.02455322,  0.03093957, -0.02838005, -0.04406847,  0.03496717,
         0.02207042, -0.00539199,  0.00158286