In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences

sent = [
    'I believe in constant growth',
    'I believe in constant Decline ',
    'Practice makes perfect',
    'Coding makes ideas come alive',
    'Success comes from daily effort',
    'Stay curious and keep exploring',
    'Hard work always beats talent',
    'Believe in yourself',
    'Focus brings clarity and direction',
    'Stay focused always',
]

In [3]:
sent

['I believe in constant growth',
 'I believe in constant Decline ',
 'Practice makes perfect',
 'Coding makes ideas come alive',
 'Success comes from daily effort',
 'Stay curious and keep exploring',
 'Hard work always beats talent',
 'Believe in yourself',
 'Focus brings clarity and direction',
 'Stay focused always']

In [4]:
## difine the vacablary size
vac_size = 10000

In [5]:
### one hot representation 
one_hot_repr = [one_hot(words, vac_size) for words in sent]
one_hot_repr

[[8654, 744, 521, 6810, 4377],
 [8654, 744, 521, 6810, 4709],
 [2505, 883, 5171],
 [1284, 883, 8176, 5432, 2667],
 [1565, 6071, 8121, 7250, 4815],
 [5930, 413, 2424, 2623, 1764],
 [9792, 8879, 3089, 9446, 2144],
 [744, 521, 1866],
 [542, 6946, 9921, 2424, 1097],
 [5930, 9683, 3089]]

In [6]:
### word Embedding Represention 

from tensorflow.keras.layers import Embedding
# from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [16]:
sent_length = 10
embededd_doc =pad_sequences(one_hot_repr,padding='pre', maxlen=sent_length)
print(embededd_doc)

[[   0    0    0    0    0 8654  744  521 6810 4377]
 [   0    0    0    0    0 8654  744  521 6810 4709]
 [   0    0    0    0    0    0    0 2505  883 5171]
 [   0    0    0    0    0 1284  883 8176 5432 2667]
 [   0    0    0    0    0 1565 6071 8121 7250 4815]
 [   0    0    0    0    0 5930  413 2424 2623 1764]
 [   0    0    0    0    0 9792 8879 3089 9446 2144]
 [   0    0    0    0    0    0    0  744  521 1866]
 [   0    0    0    0    0  542 6946 9921 2424 1097]
 [   0    0    0    0    0    0    0 5930 9683 3089]]


In [9]:
### feature represention 
dim = 9

In [23]:
model=Sequential()
model.add(Embedding(vac_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [24]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_4 (Embedding)     (None, 10, 9)             90000     
                                                                 
Total params: 90000 (351.56 KB)
Trainable params: 90000 (351.56 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [12]:
model.predict(embededd_doc)

1/1 [==============================] - 0s 157ms/step


array([[[ 0.0411639 , -0.04882349,  0.00734924,  0.04970467,
          0.04191874, -0.00173355,  0.02038412,  0.02249538,
          0.00094299],
        [ 0.0411639 , -0.04882349,  0.00734924,  0.04970467,
          0.04191874, -0.00173355,  0.02038412,  0.02249538,
          0.00094299],
        [ 0.0411639 , -0.04882349,  0.00734924,  0.04970467,
          0.04191874, -0.00173355,  0.02038412,  0.02249538,
          0.00094299],
        [ 0.0411639 , -0.04882349,  0.00734924,  0.04970467,
          0.04191874, -0.00173355,  0.02038412,  0.02249538,
          0.00094299],
        [ 0.0411639 , -0.04882349,  0.00734924,  0.04970467,
          0.04191874, -0.00173355,  0.02038412,  0.02249538,
          0.00094299],
        [-0.01522486,  0.02050293, -0.00479032,  0.02086829,
         -0.01483823,  0.04981187,  0.04080665,  0.02042082,
          0.02892232],
        [-0.0446229 , -0.02726508,  0.04962141, -0.02907591,
         -0.02717668, -0.02956222, -0.0172565 ,  0.01607298,
        

In [13]:
embededd_doc[0]

array([   0,    0,    0,    0,    0, 8654,  744,  521, 6810, 4377])

In [14]:
model.predict(embededd_doc[0])

1/1 [==============================] - 0s 30ms/step


array([[ 0.0411639 , -0.04882349,  0.00734924,  0.04970467,  0.04191874,
        -0.00173355,  0.02038412,  0.02249538,  0.00094299],
       [ 0.0411639 , -0.04882349,  0.00734924,  0.04970467,  0.04191874,
        -0.00173355,  0.02038412,  0.02249538,  0.00094299],
       [ 0.0411639 , -0.04882349,  0.00734924,  0.04970467,  0.04191874,
        -0.00173355,  0.02038412,  0.02249538,  0.00094299],
       [ 0.0411639 , -0.04882349,  0.00734924,  0.04970467,  0.04191874,
        -0.00173355,  0.02038412,  0.02249538,  0.00094299],
       [ 0.0411639 , -0.04882349,  0.00734924,  0.04970467,  0.04191874,
        -0.00173355,  0.02038412,  0.02249538,  0.00094299],
       [-0.01522486,  0.02050293, -0.00479032,  0.02086829, -0.01483823,
         0.04981187,  0.04080665,  0.02042082,  0.02892232],
       [-0.0446229 , -0.02726508,  0.04962141, -0.02907591, -0.02717668,
        -0.02956222, -0.0172565 ,  0.01607298,  0.01992461],
       [ 0.04997671, -0.02708854, -0.01637485, -0.01961141,  0