In [111]:
from tensorflow.keras.preprocessing.text import one_hot

In [112]:
### sentences

sent = [
    'I believe in constant growth',
    'I believe in constant Decline ',
    'Practice makes perfect',
    'Coding makes ideas come alive',
    'Success comes from daily effort',
    'Stay curious and keep exploring',
    'Hard work always beats talent',
    'Believe in yourself',
    'Focus brings clarity and direction',
    'Stay focused always',
]

In [113]:
sent

['I believe in constant growth',
 'I believe in constant Decline ',
 'Practice makes perfect',
 'Coding makes ideas come alive',
 'Success comes from daily effort',
 'Stay curious and keep exploring',
 'Hard work always beats talent',
 'Believe in yourself',
 'Focus brings clarity and direction',
 'Stay focused always']

In [114]:
## difine the vacablary size
vac_size = 10000

In [115]:
### one hot representation 
one_hot_repr = [one_hot(words, vac_size) for words in sent]
one_hot_repr

[[5007, 2484, 8784, 9383, 9086],
 [5007, 2484, 8784, 9383, 5056],
 [9251, 4362, 4645],
 [8971, 4362, 8095, 9836, 2395],
 [1842, 4549, 4957, 7911, 5271],
 [8409, 764, 6677, 6512, 7252],
 [7013, 5595, 7108, 7212, 8531],
 [2484, 8784, 7484],
 [6725, 4017, 8811, 6677, 4667],
 [8409, 3583, 7108]]

In [116]:
### word Embedding Represention 

from tensorflow.keras.layers import Embedding
# from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [117]:
import numpy as np

In [118]:
sent_length = 10
embededd_doc =pad_sequences(one_hot_repr,padding='pre', maxlen=sent_length)
print(embededd_doc)

[[   0    0    0    0    0 5007 2484 8784 9383 9086]
 [   0    0    0    0    0 5007 2484 8784 9383 5056]
 [   0    0    0    0    0    0    0 9251 4362 4645]
 [   0    0    0    0    0 8971 4362 8095 9836 2395]
 [   0    0    0    0    0 1842 4549 4957 7911 5271]
 [   0    0    0    0    0 8409  764 6677 6512 7252]
 [   0    0    0    0    0 7013 5595 7108 7212 8531]
 [   0    0    0    0    0    0    0 2484 8784 7484]
 [   0    0    0    0    0 6725 4017 8811 6677 4667]
 [   0    0    0    0    0    0    0 8409 3583 7108]]


In [119]:
### feature represention 
dim = 9

In [120]:
model=Sequential()
model.add(Embedding(vac_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [121]:
model.summary()

Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_9 (Embedding)     (None, 10, 9)             90000     
                                                                 
Total params: 90000 (351.56 KB)
Trainable params: 90000 (351.56 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [122]:
model.predict(embededd_doc)

1/1 [==============================] - 0s 125ms/step


array([[[-1.35141388e-02, -4.53015082e-02,  2.32380964e-02,
          2.77775861e-02,  1.59995295e-02,  4.83608954e-02,
          1.08560808e-02, -2.07780357e-02, -3.79747748e-02],
        [-1.35141388e-02, -4.53015082e-02,  2.32380964e-02,
          2.77775861e-02,  1.59995295e-02,  4.83608954e-02,
          1.08560808e-02, -2.07780357e-02, -3.79747748e-02],
        [-1.35141388e-02, -4.53015082e-02,  2.32380964e-02,
          2.77775861e-02,  1.59995295e-02,  4.83608954e-02,
          1.08560808e-02, -2.07780357e-02, -3.79747748e-02],
        [-1.35141388e-02, -4.53015082e-02,  2.32380964e-02,
          2.77775861e-02,  1.59995295e-02,  4.83608954e-02,
          1.08560808e-02, -2.07780357e-02, -3.79747748e-02],
        [-1.35141388e-02, -4.53015082e-02,  2.32380964e-02,
          2.77775861e-02,  1.59995295e-02,  4.83608954e-02,
          1.08560808e-02, -2.07780357e-02, -3.79747748e-02],
        [ 3.48613523e-02,  2.69275419e-02,  3.00743915e-02,
          1.04980581e-02, -1.795274

In [124]:
embededd_doc[0]

array([   0,    0,    0,    0,    0, 5007, 2484, 8784, 9383, 9086])

In [127]:
model.predict(embededd_doc[0])

1/1 [==============================] - 0s 50ms/step


array([[-0.01351414, -0.04530151,  0.0232381 ,  0.02777759,  0.01599953,
         0.0483609 ,  0.01085608, -0.02077804, -0.03797477],
       [-0.01351414, -0.04530151,  0.0232381 ,  0.02777759,  0.01599953,
         0.0483609 ,  0.01085608, -0.02077804, -0.03797477],
       [-0.01351414, -0.04530151,  0.0232381 ,  0.02777759,  0.01599953,
         0.0483609 ,  0.01085608, -0.02077804, -0.03797477],
       [-0.01351414, -0.04530151,  0.0232381 ,  0.02777759,  0.01599953,
         0.0483609 ,  0.01085608, -0.02077804, -0.03797477],
       [-0.01351414, -0.04530151,  0.0232381 ,  0.02777759,  0.01599953,
         0.0483609 ,  0.01085608, -0.02077804, -0.03797477],
       [ 0.03486135,  0.02692754,  0.03007439,  0.01049806, -0.01795274,
        -0.01191822,  0.02173375,  0.01693964,  0.01308891],
       [-0.01819859,  0.00183803,  0.00351216, -0.03078471,  0.01090267,
         0.0387769 , -0.04864712,  0.02218378, -0.00218717],
       [-0.00618123, -0.00574174, -0.01443586, -0.02038353, -0